import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { Outlet, RouterProvider, createRootRoute, createRoute, createRouter } from '@tanstack/solid-router'
import { For, createSignal } from 'solid-js'
import { render } from 'solid-js/web'
import './styles.css'

const listings = [
  { name: 'UR5e Collaborative Robot', maker: 'Universal Robots · Bengaluru', type: 'Buy', price: '₹18,60,000', note: 'delivery across India', image: 'https://images.unsplash.com/photo-1735494034924-f4fd13af1cea?auto=format&fit=crop&w=1100&q=85', condition: 'Excellent' },
  { name: 'DJI Matrice 350 RTK', maker: 'Dubai Enterprise Seller', type: 'Rent', price: 'AED 1,450 / day', note: 'Dubai & Abu Dhabi pickup', image: 'https://cdn.shopify.com/s/files/1/0884/4908/9829/files/Firmware_Update_Roundup_-_Early_February_1.webp?v=1732233494', condition: 'Like new' },
  { name: 'Arduino Uno R3 Starter Bundle', maker: 'Maker Lab · Mumbai', type: 'Buy', price: '₹1,850', note: 'GST invoice available', image: 'https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=1100&q=85', condition: 'New' },
  { name: 'Raspberry Pi 5 · 8GB', maker: 'Circuit Supply · Delhi', type: 'Buy', price: '₹8,900', note: 'ships in 1–2 days', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1100&q=85', condition: 'New' },
  { name: 'Soldering & Prototyping Kit', maker: 'Maker Space · Sharjah', type: 'Rent', price: 'AED 65 / week', note: 'tools and components included', image: 'https://images.unsplash.com/photo-1563770660941-10a63607692e?auto=format&fit=crop&w=1100&q=85', condition: 'Excellent' },
  { name: 'Electronics Workbench Kit', maker: 'Prototype Lab · Dubai', type: 'Rent', price: 'AED 120 / week', note: 'collection or delivery', image: 'https://images.unsplash.com/photo-1560846389-8c7e1d88eca8?auto=format&fit=crop&w=1100&q=85', condition: 'Excellent' },
]
const categories = [
  ['robot', 'Robots & automation'], ['chip', 'Arduino & boards'], ['sensor', 'Sensors & modules'], ['motor', 'Motors & actuators'], ['drone', 'Drones & aerial'],
  ['tools', 'Tools & test gear'], ['print', '3D printing'], ['wire', 'Components & wires'], ['kit', 'Kits & learning'], ['industrial', 'Lab & industrial'],
]
const faqs = [
  ['Can I rent as well as buy?', 'Yes. Sellers decide whether an item is available to buy, rent, or both. Each listing shows the available option and its terms.'],
  ['How do payments work?', 'Buyers and sellers agree on the listing terms before payment. Meka is designed around clear local payment and delivery details.'],
  ['Can I list small components?', 'Absolutely. Listings can range from industrial equipment to Arduino boards, sensors, jumper wires, tools and maker kits.'],
  ['Where is Meka available?', 'Meka currently serves buyers and sellers in India and the UAE, with local delivery or pickup agreed on each listing.'],
]
function Arrow() { return <span class="arrow" aria-hidden="true">→</span> }
function CategoryIcon(props) {
  const paths = {
    robot: <><rect x="5" y="7" width="14" height="12" rx="3" /><path d="M12 3v4M9 12h.01M15 12h.01M8 16h8M3 11h2M19 11h2" /></>,
    chip: <><rect x="6" y="6" width="12" height="12" rx="1" /><path d="M9 9h6v6H9zM9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4" /></>,
    sensor: <><circle cx="12" cy="12" r="3" /><path d="M5 5a10 10 0 0 0 0 14M19 5a10 10 0 0 1 0 14M8 8a5.7 5.7 0 0 0 0 8M16 8a5.7 5.7 0 0 1 0 8" /></>,
    motor: <><circle cx="12" cy="12" r="7" /><circle cx="12" cy="12" r="2" /><path d="M12 5V2M19 12h3M12 19v3M5 12H2" /></>,
    drone: <><path d="M8 10h8l2 4H6zM10 14l-2 5M14 14l2 5M7 8 3 5M17 8l4-3M5 5h-2M21 5h-2" /><circle cx="12" cy="12" r="1" /></>,
    tools: <><path d="m14 6 4-4 4 4-4 4M3 21l9-9M5 5l5 5M4 10l6-6" /></>,
    print: <><path d="M6 9V3h12v6M6 17H4v-6h16v6h-2M7 15h10v6H7z" /><path d="M17 13h.01" /></>,
    wire: <><path d="M5 5c4 0 4 14 8 14s4-14 8-14M3 5h2M19 5h2M11 19h4" /></>,
    kit: <><path d="M4 7h16v13H4zM4 11h16M9 7V4h6v3M8 15h3M13 15h3" /></>,
    industrial: <><path d="M3 21V9l6 3V8l6 3V5l6 4v12M7 21v-4M12 21v-4M17 21v-4" /></>,
  }
  return <svg class="category-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{paths[props.name]}</svg>
}
function ListingCard(props) { const item = () => props.item; return <article class="listing-card"><div class="listing-image"><img class="product-photo" src={item().image} alt="" /><div class="listing-tags"><span class={`transaction ${item().type.toLowerCase()}`}>{item().type}</span></div><button class="save" type="button" aria-label={`Save ${item().name}`}>♡</button></div><div class="listing-info"><p class="listing-seller">{item().maker}</p><h3>{item().name}</h3><div class="listing-price"><strong>{item().price}</strong><span>{item().type === 'Rent' ? 'Rental price' : 'Buy now'}</span></div></div></article> }
function LegalPage(props) {
  const isPrivacy = () => props.type === 'privacy'
  const sections = () => isPrivacy() ? [
    ['What we collect', 'We collect the details you provide when you create an account, contact us, or create a listing. This can include your name, contact details, listing information and transaction-related details.'],
    ['How we use information', 'We use this information to operate Meka, support marketplace activity, communicate with you, help prevent misuse, and improve the service.'],
    ['Sharing information', 'We only share information where it is needed to support a marketplace interaction, comply with applicable law, protect Meka and its users, or when you ask us to do so.'],
    ['Your choices', 'You can request access to, correction of, or deletion of personal information by contacting us. Some records may need to be retained where required by law or to resolve disputes.'],
  ] : [
    ['Using Meka', 'Meka is a marketplace for buying, renting and listing maker, electronics and automation equipment. You are responsible for providing accurate information and using the platform lawfully.'],
    ['Listings and transactions', 'Sellers are responsible for listing details, pricing, availability and fulfilment terms. Buyers should review a listing and agree delivery, pickup and payment terms before completing a transaction.'],
    ['Marketplace conduct', 'Do not use Meka to misrepresent equipment, infringe rights, send unsolicited messages, or engage in fraudulent or unsafe activity. We may limit access where these terms are not followed.'],
    ['Changes to the service', 'Meka may update the service and these terms as the marketplace evolves. Continued use after an update means you accept the revised terms.'],
  ]
  return <main class="legal-page"><header class="site-header"><a class="brand" href="/"><span class="brand-symbol">⌁</span>meka</a><nav aria-label="Primary"><a href="/#browse">Browse</a><a href="/#categories">Categories</a></nav><div class="header-actions"><a class="join-button" href="/">Back to Meka</a></div></header><article class="legal-content"><p class="overline">Meka legal</p><h1>{isPrivacy() ? 'Privacy policy' : 'Terms of use'}</h1><p class="legal-lead">Last updated: September 30, 2026. This page explains the basic rules for using Meka and the information we handle to run the marketplace.</p>{sections().map(([title, body]) => <section><h2>{title}</h2><p>{body}</p></section>)}<section><h2>Contact</h2><p>For questions about {isPrivacy() ? 'this privacy policy or your personal information' : 'these terms'}, contact <a href="mailto:hello@meka.example">hello@meka.example</a>.</p></section></article><footer class="legal-footer"><span>© 2026 Meka</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></footer></main>
}

function App() {
  const [mode, setMode] = createSignal('Buy'); const [region, setRegion] = createSignal('India'); const [howMode, setHowMode] = createSignal('buy'); const [openFaq, setOpenFaq] = createSignal(0); const shownListings = () => listings.filter((item) => item.type === mode()); const heroPrice = () => region() === 'India' ? '₹35,25,000' : 'AED 154,000'; const heroRental = () => region() === 'India' ? '₹68,000/day' : 'AED 3,100/day'; const howImages = () => howMode() === 'buy' ? ['https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=1200&q=88', 'https://images.unsplash.com/photo-1560846389-8c7e1d88eca8?auto=format&fit=crop&w=1200&q=88', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=88'] : ['https://images.unsplash.com/photo-1560846389-8c7e1d88eca8?auto=format&fit=crop&w=1200&q=88', 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=88', 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=88']
  return <main id="top">
    <header class="site-header"><a class="brand" href="#top"><span class="brand-symbol">⌁</span>meka</a><nav aria-label="Primary"><a href="#browse">Browse</a><a href="#categories">Categories</a></nav><div class="header-actions"><select class="region-picker" value={region()} onInput={(event) => setRegion(event.currentTarget.value)} aria-label="Marketplace region"><option value="India">🇮🇳 India</option><option value="UAE">🇦🇪 UAE</option></select><a class="join-button" href="#account">Sign in</a></div></header>
    <section class="hero"><div class="hero-promo"><span>Have equipment you no longer use? List it for buyers and renters across India and the UAE.</span><a href="#sell">List an item <Arrow /></a></div><div class="hero-grid"><div class="hero-art"><img class="hero-background" src="https://images.unsplash.com/photo-1735494034924-f4fd13af1cea?auto=format&fit=crop&w=1800&q=90" alt="Industrial robotic arm in a workshop" /></div><div class="hero-copy"><p class="hero-kicker">For makers, teams and labs</p><h1>Get the gear<br />your work needs.</h1><p>Search robots, boards, sensors, tools and components from verified sellers near you.</p><div class="hero-choice" role="group" aria-label="Transaction type"><button classList={{ active: mode() === 'Buy' }} onClick={() => setMode('Buy')}>I want to buy</button><button classList={{ active: mode() === 'Rent' }} onClick={() => setMode('Rent')}>I want to rent</button></div><div class="search-panel"><label><span>⌕</span><input aria-label="Search marketplace" placeholder="Search Arduino, sensors, robots, tools..." /></label><a href="#browse" class="search-button">Search <Arrow /></a></div><div class="popular-searches"><span>Popular</span><a href="#browse">Arduino Uno</a><a href="#browse">ESP32</a><a href="#browse">3D printer</a><a href="#browse">Robot arm</a></div></div></div></section>
    <section class="category-section" id="categories"><div class="section-intro"><div><p class="overline">Browse by category</p><h2>Everything for your<br /><em>next project.</em></h2></div><p>From production automation to a weekend electronics project, find the equipment and components you need.</p></div><div class="category-grid"><For each={categories}>{([icon, title]) => <a href="#browse" class="category-card"><CategoryIcon name={icon} /><h3>{title}</h3><Arrow /></a>}</For></div></section>
    <section class="listings" id="browse"><div class="listing-heading"><div><p class="overline">Featured listings</p><h2>Find your next <em>build.</em></h2></div><div class="listing-tabs"><button classList={{ selected: mode() === 'Buy' }} onClick={() => setMode('Buy')}>Buy</button><button classList={{ selected: mode() === 'Rent' }} onClick={() => setMode('Rent')}>Rent</button></div></div><div class="listing-grid"><For each={shownListings()}>{(item) => <ListingCard item={item} />}</For></div><a href="#all" class="view-all">Browse all {mode().toLowerCase()} listings <Arrow /></a></section>
    <section class="faq-section" id="faq"><div class="faq-intro"><p class="overline">Questions, answered</p><h2>Simple from<br />the <em>start.</em></h2><p>Everything you need to know before buying, renting or listing on Meka.</p></div><div class="faq-list"><For each={faqs}>{([question, answer], index) => <article classList={{ open: openFaq() === index() }}><button onClick={() => setOpenFaq(openFaq() === index() ? -1 : index())} aria-expanded={openFaq() === index()}><span>{question}</span><b>{openFaq() === index() ? '−' : '+'}</b></button><div class="faq-answer"><p>{answer}</p></div></article>}</For></div></section>
    <section class="how-section" id="how-it-works"><div class="how-heading"><h2>How it works</h2><div class="how-toggle" role="group" aria-label="Choose a marketplace journey"><button classList={{ active: howMode() === 'buy' }} onClick={() => setHowMode('buy')}>For buyers</button><button classList={{ active: howMode() === 'sell' }} onClick={() => setHowMode('sell')}>For sellers</button></div></div><div class="how-cards"><article><img src={howImages()[0]} alt={howMode() === 'buy' ? 'Electronics components' : 'Equipment prepared for listing'} /><h3>{howMode() === 'buy' ? 'Browse what you need' : 'Create a clear listing'}</h3><p>{howMode() === 'buy' ? 'Search by part, brand or category and compare verified listings.' : 'Add photos, specs and the condition of your equipment.'}</p></article><article><img src={howImages()[1]} alt={howMode() === 'buy' ? 'Electronics workshop' : 'Industrial equipment'} /><h3>{howMode() === 'buy' ? 'Choose buy or rent' : 'Choose how to list'}</h3><p>{howMode() === 'buy' ? 'Review the price, seller details and delivery or pickup terms.' : 'Set it for sale, rent, or both — entirely on your terms.'}</p></article><article><img src={howImages()[2]} alt={howMode() === 'buy' ? 'Technical equipment ready for delivery' : 'Industrial workshop'} /><h3>{howMode() === 'buy' ? 'Pay and arrange delivery' : 'Connect and get paid'}</h3><p>{howMode() === 'buy' ? 'Pay securely, then coordinate local pickup or delivery with the seller.' : 'Manage buyer enquiries and receive secure local payments.'}</p></article></div></section>
    <footer id="footer"><div class="footer-top"><a class="brand" href="#top"><span class="brand-symbol">⌁</span>meka</a><p>Buy, rent and list the gear that keeps good work moving.</p><div class="footer-links"><a href="#browse">Browse</a><a href="#categories">Categories</a><a href="#how-it-works">How it works</a><a href="#faq">Help</a></div></div><div class="footer-bottom"><span>© 2026 Meka</span><span>India · UAE</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div></footer>
  </main>
}
const rootRoute = createRootRoute({ component: () => <Outlet /> }); const indexRoute = createRoute({ getParentRoute: () => rootRoute, path: '/', component: App }); const privacyRoute = createRoute({ getParentRoute: () => rootRoute, path: '/privacy', component: () => <LegalPage type="privacy" /> }); const termsRoute = createRoute({ getParentRoute: () => rootRoute, path: '/terms', component: () => <LegalPage type="terms" /> }); const router = createRouter({ routeTree: rootRoute.addChildren([indexRoute, privacyRoute, termsRoute]) }); const queryClient = new QueryClient(); render(() => <QueryClientProvider client={queryClient}><RouterProvider router={router} /></QueryClientProvider>, document.getElementById('root'))
